# The current settings are based on:
#
# https://www.jetbrains.com/lp/devecosystem-2019/ruby/
language: ruby

# Supporting Ruby 2.1+ covers almost the whole market. Over 10% of apps are on
# Rails 4.2 so we'll continue to support it.
matrix:
  include:
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.4.9
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.5.7
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.6.5
      gemfile: gemfiles/Gemfile.rails-4.2.x

    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.4.9
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.5.7
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.6.5
      gemfile: gemfiles/Gemfile.rails-5.0.x

    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-5.1.x
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile.rails-5.1.x
    - rvm: 2.4.9
      gemfile: gemfiles/Gemfile.rails-5.1.x
    - rvm: 2.5.7
      gemfile: gemfiles/Gemfile.rails-5.1.x
    - rvm: 2.6.5
      gemfile: gemfiles/Gemfile.rails-5.1.x

    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-5.2.x
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile.rails-5.2.x
    - rvm: 2.4.9
      gemfile: gemfiles/Gemfile.rails-5.2.x
    - rvm: 2.5.7
      gemfile: gemfiles/Gemfile.rails-5.2.x
    - rvm: 2.6.5
      gemfile: gemfiles/Gemfile.rails-5.2.x

    - rvm: 2.5.7
      gemfile: gemfiles/Gemfile.rails-6.0.x
    - rvm: 2.6.5
      gemfile: gemfiles/Gemfile.rails-6.0.x

services:
  - postgresql

before_install:
  - gem uninstall -v '>=2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '1.17.3'

before_script:
  - cp test/dummy/config/database.yml.travis test/dummy/config/database.yml
  - bundle exec rake --rakefile test/dummy/Rakefile db:create db:migrate
