# The current settings are based on:
#
# https://www.jetbrains.com/lp/devecosystem-2019/ruby/
language: ruby

env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost:5432/active_record_doctor_test

# Supporting Ruby 2.1+ covers almost the whole market. Over 10% of apps are on
# Rails 4.2 so we'll continue to support it.
matrix:
  include:
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.4.9
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.5.8
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.6.6
      gemfile: gemfiles/Gemfile.rails-4.2.x

    # We skip 2.7.1 since it ships with Bundler 2 and Rails 4.2 explicitly
    # depends upon Bundler 1. The build should be fixable but we're assuming
    # most Rails 4.2 apps simply won't update to Ruby 2.7.

    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-5.2.x
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile.rails-5.2.x
    - rvm: 2.4.9
      gemfile: gemfiles/Gemfile.rails-5.2.x
    - rvm: 2.5.8
      gemfile: gemfiles/Gemfile.rails-5.2.x
    - rvm: 2.6.6
      gemfile: gemfiles/Gemfile.rails-5.2.x
    - rvm: 2.7.1
      gemfile: gemfiles/Gemfile.rails-5.2.x

    - rvm: 2.5.8
      gemfile: gemfiles/Gemfile.rails-6.0.x
    - rvm: 2.6.6
      gemfile: gemfiles/Gemfile.rails-6.0.x
    - rvm: 2.7.1
      gemfile: gemfiles/Gemfile.rails-6.0.x

services:
  - postgresql

before_install:
  - gem uninstall -v '>=2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '1.17.3'

before_script:
  - createdb active_record_doctor_test
